eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
petclinic-ignite:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 10000